version: '2'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: node_modules/.bin/nodemon .
    links:
      - db
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app/app
      - /home/app/app/node_modules
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
